"use strict";
var __cov_uis5liiuDAmpsG1B_v_bZA = (Function('return this'))();
if (!__cov_uis5liiuDAmpsG1B_v_bZA.__coverage__) { __cov_uis5liiuDAmpsG1B_v_bZA.__coverage__ = {}; }
__cov_uis5liiuDAmpsG1B_v_bZA = __cov_uis5liiuDAmpsG1B_v_bZA.__coverage__;
if (!(__cov_uis5liiuDAmpsG1B_v_bZA['src/core/renderer.js'])) {
   __cov_uis5liiuDAmpsG1B_v_bZA['src/core/renderer.js'] = {"path":"src/core/renderer.js","s":{"1":0,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0},"b":{"1":[0,0],"2":[0,0]},"f":{"1":0},"fnMap":{"1":{"name":"(anonymous_1)","line":6,"loc":{"start":{"line":6,"column":30},"end":{"line":6,"column":55}}}},"statementMap":{"1":{"start":{"line":6,"column":1},"end":{"line":46,"column":3}},"2":{"start":{"line":7,"column":5},"end":{"line":7,"column":23}},"3":{"start":{"line":14,"column":5},"end":{"line":19,"column":6}},"4":{"start":{"line":15,"column":9},"end":{"line":18,"column":12}},"5":{"start":{"line":21,"column":5},"end":{"line":24,"column":44}},"6":{"start":{"line":27,"column":5},"end":{"line":35,"column":42}},"7":{"start":{"line":37,"column":5},"end":{"line":37,"column":46}},"8":{"start":{"line":41,"column":5},"end":{"line":43,"column":17}},"9":{"start":{"line":45,"column":5},"end":{"line":45,"column":16}}},"branchMap":{"1":{"line":7,"type":"binary-expr","locations":[{"start":{"line":7,"column":12},"end":{"line":7,"column":16}},{"start":{"line":7,"column":20},"end":{"line":7,"column":22}}]},"2":{"line":14,"type":"if","locations":[{"start":{"line":14,"column":5},"end":{"line":14,"column":5}},{"start":{"line":14,"column":5},"end":{"line":14,"column":5}}]}}};
}
__cov_uis5liiuDAmpsG1B_v_bZA = __cov_uis5liiuDAmpsG1B_v_bZA['src/core/renderer.js'];
__cov_uis5liiuDAmpsG1B_v_bZA.s['1']++;Marionette.Renderer.render=function(template,data){__cov_uis5liiuDAmpsG1B_v_bZA.f['1']++;__cov_uis5liiuDAmpsG1B_v_bZA.s['2']++;data=(__cov_uis5liiuDAmpsG1B_v_bZA.b['1'][0]++,data)||(__cov_uis5liiuDAmpsG1B_v_bZA.b['1'][1]++,{});__cov_uis5liiuDAmpsG1B_v_bZA.s['3']++;if(!template){__cov_uis5liiuDAmpsG1B_v_bZA.b['2'][0]++;__cov_uis5liiuDAmpsG1B_v_bZA.s['4']++;throw new Marionette.Error({name:'TemplateNotFoundError',message:'Cannot render the template since its false, null or undefined.'});}else{__cov_uis5liiuDAmpsG1B_v_bZA.b['2'][1]++;}__cov_uis5liiuDAmpsG1B_v_bZA.s['5']++;var compiler=Jskeleton.htmlBars.compiler,DOMHelper=Jskeleton.htmlBars.DOMHelper,hooks=Jskeleton.htmlBars.hooks,render=Jskeleton.htmlBars.render;__cov_uis5liiuDAmpsG1B_v_bZA.s['6']++;var templateSpec=compiler.compileSpec(template,{}),templatePreCompiled=compiler.template(templateSpec),env={dom:new DOMHelper(),hooks:hooks,helpers:Jskeleton._helpers,jskeleton:data.enviroment},scope=hooks.createFreshScope();__cov_uis5liiuDAmpsG1B_v_bZA.s['7']++;hooks.bindSelf(env,scope,data.context);__cov_uis5liiuDAmpsG1B_v_bZA.s['8']++;var dom=render(templatePreCompiled,env,scope,{}).fragment;__cov_uis5liiuDAmpsG1B_v_bZA.s['9']++;return dom;};
