"use strict";
var __cov_HH5haUgwJro7mY3FaPutHA = (Function('return this'))();
if (!__cov_HH5haUgwJro7mY3FaPutHA.__coverage__) { __cov_HH5haUgwJro7mY3FaPutHA.__coverage__ = {}; }
__cov_HH5haUgwJro7mY3FaPutHA = __cov_HH5haUgwJro7mY3FaPutHA.__coverage__;
if (!(__cov_HH5haUgwJro7mY3FaPutHA['src/core/service.js'])) {
   __cov_HH5haUgwJro7mY3FaPutHA['src/core/service.js'] = {"path":"src/core/service.js","s":{"1":0,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0},"b":{"1":[0,0],"2":[0,0]},"f":{"1":0},"fnMap":{"1":{"name":"(anonymous_1)","line":9,"loc":{"start":{"line":9,"column":17},"end":{"line":9,"column":32}}}},"statementMap":{"1":{"start":{"line":8,"column":0},"end":{"line":23,"column":3}},"2":{"start":{"line":10,"column":8},"end":{"line":12,"column":63}},"3":{"start":{"line":14,"column":8},"end":{"line":14,"column":56}},"4":{"start":{"line":16,"column":8},"end":{"line":16,"column":74}},"5":{"start":{"line":18,"column":8},"end":{"line":20,"column":9}},"6":{"start":{"line":19,"column":12},"end":{"line":19,"column":51}},"7":{"start":{"line":25,"column":0},"end":{"line":25,"column":28}}},"branchMap":{"1":{"line":10,"type":"binary-expr","locations":[{"start":{"line":10,"column":22},"end":{"line":10,"column":26}},{"start":{"line":10,"column":30},"end":{"line":10,"column":32}}]},"2":{"line":18,"type":"if","locations":[{"start":{"line":18,"column":8},"end":{"line":18,"column":8}},{"start":{"line":18,"column":8},"end":{"line":18,"column":8}}]}}};
}
__cov_HH5haUgwJro7mY3FaPutHA = __cov_HH5haUgwJro7mY3FaPutHA['src/core/service.js'];
__cov_HH5haUgwJro7mY3FaPutHA.s['1']++;var Service=Marionette.Object.extend({constructor:function(opts){__cov_HH5haUgwJro7mY3FaPutHA.f['1']++;__cov_HH5haUgwJro7mY3FaPutHA.s['2']++;var options=(__cov_HH5haUgwJro7mY3FaPutHA.b['1'][0]++,opts)||(__cov_HH5haUgwJro7mY3FaPutHA.b['1'][1]++,{}),serviceOptions=['model','collection','events'];__cov_HH5haUgwJro7mY3FaPutHA.s['3']++;_.extend(this,_.pick(options,serviceOptions));__cov_HH5haUgwJro7mY3FaPutHA.s['4']++;this.options=_.extend({},this.options,this.defaults,options);__cov_HH5haUgwJro7mY3FaPutHA.s['5']++;if(_.isFunction(this.initialize)){__cov_HH5haUgwJro7mY3FaPutHA.b['2'][0]++;__cov_HH5haUgwJro7mY3FaPutHA.s['6']++;this.initialize.apply(this,arguments);}else{__cov_HH5haUgwJro7mY3FaPutHA.b['2'][1]++;}}});__cov_HH5haUgwJro7mY3FaPutHA.s['7']++;Jskeleton.Service=Service;
